services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_USER: electronica       
      POSTGRES_PASSWORD: electronica123 
      POSTGRES_DB: vision     
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data: